# Render.com deployment configuration
services:
  # API Web Service
  - type: web
    name: swipehire-api
    env: node
    plan: free  # Use 'starter' for production
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://swipehire.vercel.app
      - key: SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard  
      - key: JWT_SECRET
        generateValue: true  # Auto-generate secure secret

  # Background Scraper Worker
  - type: worker
    name: swipehire-scraper
    env: docker
    plan: free
    dockerfilePath: ./scraper/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false  # Set manually in Render dashboard
      - key: CITIES
        value: vancouver,toronto,calgary
      - key: SCRAPE_INTERVAL_HOURS
        value: 6
      - key: MAX_JOBS_PER_CITY
        value: 100
      - key: DEBUG
        value: false
      - key: RUN_ONCE
        value: false