name: Daily Job Scraper

on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Install dependencies
      run: |
        cd scraper
        pip install -r requirements.txt
        
    - name: Run job scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        CITIES: vancouver,toronto,calgary
        MAX_JOBS_PER_CITY: 20
        RUN_ONCE: true
        DEBUG: false
      run: |
        cd scraper
        python main.py